apiVersion: v1
kind: Service
metadata:
  namespace: vrd-dev
  name: redis-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
